plugins {
	id 'net.neoforged.moddev' version "2.0.80"
	id 'com.almostreliable.almostgradle' version "1.4.1"
}

almostgradle.setup {
	it.withSourcesJar = false
	it.dataGen = true
}

neoForge {
	//interfaceInjectionData.from("src/main/resources/interfaces.json")
}

repositories {
	maven {
		name = "Shadows (Placebo)"
		url = "https://maven.shadowsoffire.dev/releases"
	}
	maven {
		name = "TerraformersMC"
		url = "https://maven.terraformersmc.com"
	}
	mavenCentral()
}

dependencies {
	jarJar(implementation("dev.shadowsoffire:Placebo")) {
		version {
			strictly '[1.21.1-9.8.0,)'
			prefer '1.21.1-9.9.0'
		}
	}
}
