org.gradle.jvmargs=-Xmx3G
loom.platform=neoforge
minecraft_version=1.21.1
maven_group=ky.someone.mods
archives_base_name=gag
mod_version=5.1.0
mod_name=GAG
mod_id=gag
curseforge_id=694962
artifact_type=release
emi_version=1.1.22+1.21.1
neoforge_version=21.1.193
parchment_version=2024.11.17
org.gradle.configuration-cache=true
