modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "gag"
version = "${version}"
displayName = "Gadgets Against Grind"
authors = "MaxNeedsSnacks"
description = '''
A Minecraft mod that adds various different utility items and blocks!
'''
#logoFile = ""

[[dependencies.gag]]
modId = "neoforge"
type = "required"
versionRange = "[21.0.114-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gag]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gag]]
modId = "architectury"
type = "required"
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "gag.mixins.json"
