modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/${githubUser}/${githubRepo}/issues"
license = "${license}"

[[mixins]]
config = "${modId}.mixins.json"

[[mods]]
modId = "${modId}"
version = "${version}"
displayName = "${modName}"
authors = "${modAuthor}"
description = '''${modDescription}'''
featureFlags = "META-INF/feature_flags.json"

[[dependencies."${modId}"]]
modId = "minecraft"
type = "REQUIRED"
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${modId}"]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[${neoforgeVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${modId}"]]
modId = "placebo"
type = "required"
versionRange = "[9.8.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${modId}"]]
modId = "jei"
type = "OPTIONAL"
versionRange = "[${jeiVersion},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${modId}"]]
modId = "emi"
type = "OPTIONAL"
versionRange = "[${emiVersion},)"
ordering = "AFTER"
side = "BOTH"